# Generated by Django 4.0.6 on 2022-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0002_category_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='ctype',
            field=models.CharField(max_length=100),
        ),
    ]
