# Generated by Django 4.0.6 on 2022-12-25 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0003_alter_category_cname_alter_category_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
