# Generated by Django 4.0.6 on 2022-12-29 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0004_category_cdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edetail', models.TextField(max_length=500)),
                ('eamount', models.IntegerField()),
                ('edate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
