# Generated by Django 4.0.6 on 2022-12-29 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('idetail', models.TextField(max_length=500)),
                ('iamount', models.IntegerField()),
                ('idate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
