# Generated by Django 4.0.6 on 2023-01-02 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0006_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_date', models.DateField()),
            ],
        ),
    ]
