<<<<<<< HEAD
# Generated by Django 4.0.6 on 2023-01-03 14:50

import datetime
=======
# Generated by Django 4.1.3 on 2023-01-03 11:32

>>>>>>> b490797657ff47b657d5a5611206c7c3f2b4c1d3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0007_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date.today),
=======
            field=models.DateField(verbose_name='Date'),
>>>>>>> b490797657ff47b657d5a5611206c7c3f2b4c1d3
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date.today),
=======
            field=models.DateField(verbose_name='Date'),
>>>>>>> b490797657ff47b657d5a5611206c7c3f2b4c1d3
        ),
    ]
