# Generated by Django 4.1.3 on 2023-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0007_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
