# Generated by Django 4.0.6 on 2023-01-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0008_alter_group_end_date_alter_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(),
        ),
    ]
