# Generated by Django 4.0.6 on 2023-01-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0009_group_isactivated_alter_group_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='groupID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.group'),
        ),
    ]
