# Generated by Django 4.0.6 on 2023-01-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0010_income_groupid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='iamount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='idate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='idetail',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='income',
            name='iname',
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.category'),
        ),
    ]
