# Generated by Django 4.0.6 on 2023-01-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0011_rename_iamount_income_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='detail',
            new_name='description',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
