# Generated by Django 4.0.6 on 2023-01-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0012_rename_detail_income_description_income_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ctype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='eamount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='edate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='edetail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='gname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='groupID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.group'),
        ),
    ]
