# Generated by Django 4.0.6 on 2023-01-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0013_rename_cdate_category_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='detail',
            new_name='description',
        ),
    ]
