# Generated by Django 4.0.6 on 2023-01-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0013_alter_expense_groupid_alter_income_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='groupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.group'),
        ),
        migrations.AlterField(
            model_name='income',
            name='groupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBackend.group'),
        ),
    ]
