# Generated by Django 4.0.6 on 2023-01-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0014_alter_expense_groupid_alter_income_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='groupID',
        ),
        migrations.RemoveField(
            model_name='income',
            name='groupID',
        ),
    ]
