# Generated by Django 4.0.6 on 2023-01-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0014_rename_detail_expense_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='groupID',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='groupID',
            new_name='group',
        ),
    ]
